name: Backend Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

defaults:
  run:
    working-directory: ./backend

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"
      - name: Restore dependencies
        run: dotnet restore
      - name: Run backend tests
        run: dotnet test --configuration Release
