name: Frontend tests
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
